export type MusicGeneCategoryId =
  | "skeleton"
  | "groove"
  | "bass"
  | "harmony"
  | "texture"
  | "timbre"
  | "behavior"
  | "arrangement";

export interface MusicGene {
  id: string;
  name: string;
  definition: string;
  effect: string;
  type: string;
  promptCue: string;
}

export interface MusicGeneCategory {
  id: MusicGeneCategoryId;
  label: string;
  hint: string;
  genes: MusicGene[];
}

function gene(
  id: string,
  name: string,
  definition: string,
  effect: string,
  type: string,
  promptCue: string,
): MusicGene {
  return { id, name, definition, effect, type, promptCue };
}

export const musicGeneCategories: MusicGeneCategory[] = [
  {
    id: "skeleton",
    label: "Skeleton",
    hint: "Rhythmic frame",
    genes: [
      gene(
        "four-on-floor-kick",
        "4/4 kick",
        "四拍地板底鼓骨架",
        "决定最基础的推进感",
        "rhythm / skeleton",
        "Use a four-on-the-floor kick pulse as the rhythmic spine.",
      ),
      gene(
        "broken-beat",
        "broken beat",
        "非四拍地板、切分更明显的鼓骨架",
        "让律动更碎、更游移",
        "rhythm / skeleton",
        "Use syncopated, non-four-on-the-floor drum placement.",
      ),
      gene(
        "half-time-snare",
        "half-time snare",
        "军鼓落点更稀疏，整体听感更慢更重",
        "拉开空间感和重量感",
        "rhythm / skeleton",
        "Place the snare in a half-time feel with heavier spacing.",
      ),
      gene(
        "backbeat",
        "backbeat",
        "军鼓强调二四拍的基础流行/放克骨架",
        "让节奏稳定、容易进入",
        "rhythm / skeleton",
        "Use a clear snare backbeat on beats two and four.",
      ),
      gene(
        "four-on-floor-clap",
        "4/4 clap lift",
        "四拍底鼓上叠加 clap 或 snare 的抬升",
        "增强 house / disco 的舞池推动",
        "rhythm / skeleton",
        "Layer claps or snares over a four-on-the-floor pulse for lift.",
      ),
      gene(
        "two-step",
        "2-step",
        "kick/snare 错开、带 UK garage 感的双步骨架",
        "制造轻盈、弹跳的俱乐部游移感",
        "rhythm / skeleton",
        "Use a two-step kick and snare skeleton with skipped downbeats.",
      ),
      gene(
        "amen-break",
        "break chop",
        "切片式 breakbeat 鼓组骨架",
        "带来 jungle / drum and bass 的高速能量",
        "rhythm / skeleton",
        "Use chopped breakbeat logic with fast ghost hits and edits.",
      ),
      gene(
        "tresillo",
        "tresillo pulse",
        "3-3-2 的拉丁/舞曲重音分布",
        "让节奏有前倾和跨文化律动",
        "rhythm / skeleton",
        "Use a tresillo-like 3-3-2 accent pulse.",
      ),
      gene(
        "reggaeton-dembow",
        "dembow",
        "reggaeton 常见 kick/snare 重音骨架",
        "形成身体感很强的摇摆推进",
        "rhythm / skeleton",
        "Use a dembow-inspired kick and snare pattern.",
      ),
    ],
  },
  {
    id: "groove",
    label: "Groove",
    hint: "Timing feel",
    genes: [
      gene(
        "swing",
        "swing",
        "拍点不是完全笔直，而是有摆动",
        "让 groove 更活",
        "groove",
        "Add swung timing and off-grid rhythmic feel.",
      ),
      gene(
        "shuffle",
        "shuffle",
        "三连音感的摇摆节奏",
        "让节奏更滚动、更蓝调",
        "groove",
        "Use a shuffle feel with triplet-weighted subdivisions.",
      ),
      gene(
        "tight-grid",
        "tight grid",
        "拍点贴近网格，几乎不拖不抢",
        "让律动更机械、更精确",
        "groove",
        "Keep timing tight, quantized, and grid-forward.",
      ),
      gene(
        "laid-back",
        "laid-back pocket",
        "军鼓、和弦或低音略微靠后",
        "制造松弛、慵懒和 head-nod 感",
        "groove",
        "Make the groove feel laid-back with late-feeling accents.",
      ),
      gene(
        "pushed",
        "pushed feel",
        "关键音符或低音略微提前进入",
        "让循环更急迫、更向前冲",
        "groove",
        "Use anticipation and pushed accents to drive forward motion.",
      ),
      gene(
        "ghost-notes",
        "ghost notes",
        "低音量的鼓点或装饰音藏在主拍之间",
        "增加人味和细密律动",
        "groove",
        "Add quiet ghost notes between the main drum hits.",
      ),
      gene(
        "velocity-contour",
        "velocity contour",
        "同一声部的力度有规律起伏",
        "让机械重复变得有呼吸",
        "groove",
        "Shape repeated hits with alternating velocity and accents.",
      ),
      gene(
        "offbeat-lift",
        "offbeat lift",
        "反拍 hi-hat、chord 或 bass 强调",
        "制造 dance music 的弹跳和上扬",
        "groove",
        "Emphasize offbeats with hats, chords, or bass movement.",
      ),
    ],
  },
  {
    id: "bass",
    label: "Bass",
    hint: "Low-end DNA",
    genes: [
      gene(
        "funk-bass",
        "funk bass",
        "切分、弹跳、带空隙的低音线",
        "让音乐更有身体感和弹性",
        "bass",
        "Write a syncopated funk bassline with rests and bounce.",
      ),
      gene(
        "acid-bass",
        "acid bass",
        "共振滤波、滑音、重复的酸性低音",
        "带来 acid / club 的咬合感",
        "bass",
        "Use a resonant acid bass pattern with filter movement.",
      ),
      gene(
        "sub-bass",
        "sub bass",
        "低频为主、音色简洁的根音支撑",
        "增加重量和俱乐部下潜感",
        "bass",
        "Anchor the track with clean, deep sub bass.",
      ),
      gene(
        "walking-bass",
        "walking bass",
        "连续移动、连接和声的低音线",
        "制造爵士或复古行进感",
        "bass",
        "Use a walking bassline that connects chord tones.",
      ),
      gene(
        "reese-bass",
        "reese bass",
        "失谐、宽厚、带相位运动的低音",
        "制造 drum and bass / bass music 的压迫感",
        "bass",
        "Use a wide detuned reese bass with slow movement.",
      ),
      gene(
        "808-glide",
        "808 glide",
        "长尾 808 低音带滑音和音高弯曲",
        "形成 trap / drill 的重量和旋律性",
        "bass",
        "Use long 808 notes with slides and pitch movement.",
      ),
      gene(
        "rubber-bass",
        "rubber bass",
        "短促、弹性、滤波包络明显的低音",
        "带来 nu-disco / electro-funk 弹跳",
        "bass",
        "Use a short rubbery bass with plucky filter envelopes.",
      ),
      gene(
        "pedal-bass",
        "pedal bass",
        "长时间停留在根音或单一低音支点",
        "让上层和声变化但低频保持稳定",
        "bass",
        "Hold a pedal bass tone while upper layers move.",
      ),
      gene(
        "call-response-bass",
        "call-response bass",
        "低音短句之间有问答关系",
        "增强循环记忆点和律动对话",
        "bass",
        "Make the bassline answer itself with call-and-response phrases.",
      ),
    ],
  },
  {
    id: "harmony",
    label: "Harmony",
    hint: "Chord mood",
    genes: [
      gene(
        "jazzy-chord",
        "jazzy chord",
        "七和弦、九和弦或更丰富的和声色彩",
        "让音乐更温暖、更复杂",
        "harmony",
        "Use extended jazzy chords and voicings.",
      ),
      gene(
        "minor-mood",
        "minor mood",
        "小调或偏暗的调式中心",
        "制造阴影、张力或夜晚感",
        "harmony",
        "Lean into a minor-mode harmonic mood.",
      ),
      gene(
        "bright-major",
        "bright major",
        "大调、明亮、上扬的和声重心",
        "让旋律更开放、更积极",
        "harmony",
        "Use bright major harmony with open, optimistic color.",
      ),
      gene(
        "modal-dorian",
        "dorian color",
        "小调底色中带明亮六级的调式感",
        "适合 funk、house、neo-soul 的微亮阴影",
        "harmony",
        "Use a dorian modal color with minor warmth and a bright sixth.",
      ),
      gene(
        "modal-phrygian",
        "phrygian tension",
        "半音下行的异域小调张力",
        "制造 dark、cinematic 或 club tension",
        "harmony",
        "Use phrygian-flavored tension and close semitone movement.",
      ),
      gene(
        "sus-chords",
        "sus chords",
        "悬挂和弦弱化大小调明确性",
        "让和声更漂浮、更开放",
        "harmony",
        "Use suspended chords to keep the harmony open.",
      ),
      gene(
        "chromatic-passing",
        "chromatic passing",
        "半音经过音连接主音或和弦音",
        "增加爵士、acid 或 bassline 的滑动感",
        "harmony",
        "Use chromatic passing tones to connect stable notes.",
      ),
      gene(
        "pedal-harmony",
        "pedal harmony",
        "固定根音上方移动不同和声",
        "制造悬浮、循环和张力堆叠",
        "harmony",
        "Move chords over a stable pedal tone.",
      ),
      gene(
        "power-chords",
        "power chords",
        "五度和弦弱化三音色彩",
        "带来 rock、industrial 或 rave 的硬边缘",
        "harmony",
        "Use fifth-based power chords for a harder harmonic edge.",
      ),
    ],
  },
  {
    id: "texture",
    label: "Texture",
    hint: "Space layer",
    genes: [
      gene(
        "pad-wash",
        "pad wash",
        "铺底、延展、模糊边界的和声垫",
        "增加空间、空气和连贯感",
        "texture",
        "Add a soft pad wash for width and atmosphere.",
      ),
      gene(
        "grain-cloud",
        "grain cloud",
        "颗粒化、碎片化、雾状的声音云",
        "让背景更梦幻、实验和流动",
        "texture",
        "Use grainy cloud-like fragments behind the main groove.",
      ),
      gene(
        "vinyl-noise",
        "vinyl noise",
        "轻微噪声、底噪或老唱片颗粒",
        "增加 lo-fi、采样和温度",
        "texture",
        "Add subtle vinyl-style noise or low-level texture.",
      ),
      gene(
        "field-recording",
        "field bed",
        "环境录音或生活声作为底床",
        "给循环一个具体空间和叙事入口",
        "texture",
        "Place a subtle field-recording bed under the musical layers.",
      ),
      gene(
        "dub-space",
        "dub space",
        "大片 delay / reverb 尾音塑造空间",
        "让音乐更深、更松散、更回声化",
        "texture",
        "Use dubby delay and reverb throws for depth.",
      ),
      gene(
        "air-layer",
        "air layer",
        "高频空气声、噪声或 shimmer 层",
        "增加亮度、呼吸和宽度",
        "texture",
        "Add a thin high-frequency air layer for shimmer.",
      ),
      gene(
        "drone-bed",
        "drone bed",
        "持续音或根音长时间铺底",
        "制造催眠、仪式感和调性锚点",
        "texture",
        "Use a sustained drone bed as a tonal anchor.",
      ),
      gene(
        "reverse-swell",
        "reverse swell",
        "反向上升或吸入式过渡音",
        "推动段落进入下一拍或下一句",
        "texture",
        "Use reverse swells to pull into important hits.",
      ),
    ],
  },
  {
    id: "timbre",
    label: "Timbre",
    hint: "Sound color",
    genes: [
      gene(
        "dusty-drums",
        "dusty drums",
        "带颗粒、旧采样或轻微失真的鼓声",
        "增加复古、lo-fi 和采样感",
        "timbre",
        "Make the drums dusty, sampled, and slightly worn.",
      ),
      gene(
        "crispy-hats",
        "crispy hats",
        "明亮、清脆、存在感强的 hi-hat",
        "提升速度感和高频细节",
        "timbre",
        "Use crisp hi-hats with clear high-frequency motion.",
      ),
      gene(
        "acid-tone",
        "acid tone",
        "高共振、咬耳、会扫动的合成器音色",
        "制造电子、锐利、迷幻的质感",
        "timbre",
        "Use a resonant acid synth tone with animated filtering.",
      ),
      gene(
        "warm-analog",
        "warm analog",
        "圆润、轻微失谐、不过分锋利的合成器",
        "让声音更厚、更亲近",
        "timbre",
        "Use warm analog-style synth tones with subtle detune.",
      ),
      gene(
        "fm-glass",
        "FM glass",
        "金属、玻璃感、谐波清晰的 FM 音色",
        "增加冷感、亮度和数字质感",
        "timbre",
        "Use glassy FM-like tones for metallic brightness.",
      ),
      gene(
        "bitcrushed",
        "bitcrushed",
        "低比特或采样率降低的破碎质感",
        "制造游戏机、dirty 或实验边缘",
        "timbre",
        "Add bitcrushed or reduced-sample-rate coloration.",
      ),
      gene(
        "plucky-synth",
        "plucky synth",
        "短 attack、短 decay 的拨弦式合成器",
        "让旋律更清楚、更有弹性",
        "timbre",
        "Use short plucky synth envelopes for rhythmic melodic parts.",
      ),
      gene(
        "supersaw-wide",
        "wide supersaw",
        "多振荡器失谐形成的宽厚锯齿波",
        "带来 trance / EDM 的大面积亮度",
        "timbre",
        "Use wide detuned supersaw tones for large harmonic presence.",
      ),
      gene(
        "soft-keys",
        "soft keys",
        "柔和电钢、键盘或 muted chord 音色",
        "让和声更温暖、更亲密",
        "timbre",
        "Use soft key-like tones for warm chord support.",
      ),
    ],
  },
  {
    id: "behavior",
    label: "Behavior",
    hint: "Loop logic",
    genes: [
      gene(
        "hypnotic-loop",
        "hypnotic loop",
        "重复性强、细节慢慢变化的循环",
        "形成沉浸、催眠、club 里的锁定感",
        "behavior",
        "Build a hypnotic loop that stays locked but compelling.",
      ),
      gene(
        "micro-variation",
        "micro variation",
        "小概率、小幅度的节奏或音色变化",
        "避免循环僵硬，同时不破坏稳定性",
        "behavior",
        "Add small probabilistic variations without destabilizing the groove.",
      ),
      gene(
        "call-response",
        "call response",
        "两个声部或短句交替回应",
        "让循环像对话而不是平铺",
        "behavior",
        "Create call-and-response between two musical layers.",
      ),
      gene(
        "filter-evolution",
        "filter evolution",
        "滤波器随时间慢慢打开、关闭或摆动",
        "制造渐进变化和 build-up",
        "behavior",
        "Animate filter cutoff slowly across the loop.",
      ),
      gene(
        "polyrhythm",
        "polyrhythm",
        "不同声部使用不同周期或步数",
        "产生复杂但可循环的错位关系",
        "behavior",
        "Layer patterns with different step lengths or cycles.",
      ),
      gene(
        "euclidean-spark",
        "euclidean spark",
        "用均匀分布的节奏点制造装饰层",
        "增加非直觉但自然的打击乐运动",
        "behavior",
        "Use Euclidean rhythms for auxiliary percussion or accents.",
      ),
      gene(
        "random-drop",
        "random drop",
        "部分音符以小概率消失",
        "保持循环活性并制造轻微惊喜",
        "behavior",
        "Use controlled random drops on hats, percussion, or fills.",
      ),
      gene(
        "phase-drift",
        "phase drift",
        "相近但不同长度的循环慢慢错位",
        "制造 Reich 式流动和长期变化",
        "behavior",
        "Let one layer phase against another with a slightly different cycle.",
      ),
    ],
  },
  {
    id: "arrangement",
    label: "Arrangement",
    hint: "Pattern events",
    genes: [
      gene(
        "stabs",
        "stabs",
        "短促、切入式的和弦或采样点缀",
        "制造呼应、强调和段落感",
        "arrangement",
        "Add short stabs as rhythmic arrangement accents.",
      ),
      gene(
        "fill-every-four",
        "4-bar fill",
        "每四小节或固定周期出现鼓 fill",
        "帮助循环产生段落边界",
        "arrangement",
        "Add a small fill or variation every fourth cycle.",
      ),
      gene(
        "breakdown-gap",
        "breakdown gap",
        "短暂抽掉 kick、bass 或主鼓",
        "制造呼吸和重新进入的冲击",
        "arrangement",
        "Create brief gaps where the main groove drops out.",
      ),
      gene(
        "riser",
        "riser",
        "上升音高、噪声或滤波推动过渡",
        "提示即将进入新段落",
        "arrangement",
        "Use a riser or upward motion before the next section.",
      ),
      gene(
        "drop-hit",
        "drop hit",
        "重拍处加入 crash、impact 或重音",
        "强化段落落点和能量释放",
        "arrangement",
        "Mark important downbeats with a strong drop hit.",
      ),
      gene(
        "mute-play",
        "mute play",
        "声部轮流静音/返回",
        "让简单材料通过进出场形成编排",
        "arrangement",
        "Use layer muting and re-entry as arrangement movement.",
      ),
      gene(
        "hook-repeat",
        "hook repeat",
        "短 hook 反复出现但略有变化",
        "提升记忆点和可识别度",
        "arrangement",
        "Repeat a short hook with small variations.",
      ),
      gene(
        "percussion-answer",
        "percussion answer",
        "主鼓之后由小打击乐回应",
        "填补空隙并增加舞动细节",
        "arrangement",
        "Let percussion answer the main kick and snare pattern.",
      ),
    ],
  },
];

export const musicGenes = musicGeneCategories.flatMap((category) =>
  category.genes.map((item) => ({ ...item, category: category.id })),
);

export type MusicGeneWithCategory = (typeof musicGenes)[number];

export function getMusicGenesByIds(ids: string[]): MusicGeneWithCategory[] {
  const selected = new Set(ids);
  return musicGenes.filter((item) => selected.has(item.id));
}
